scalacenter/scala-debug-adapter

- build.sbt
- core/src/test/resources/BreakpointTest.java
- sbt-dap-plugin/src/main/scala/dap/DebugAdapterPlugin.scala
- sbt-dap-plugin/src/main/scala/dap/DebuggeeProcess.scala
- sbt-dap-plugin/src/main/scala/dap/SbtDebuggeeRunner.scala
- sbt-dap-plugin/src/main/scala/dap/SbtLoggerAdapter.scala
- sbt-dap-plugin/src/sbt-test/attach/breakpoints/build.sbt
- sbt-dap-plugin/src/sbt-test/attach/breakpoints/project/plugins.sbt
- sbt-dap-plugin/src/sbt-test/attach/breakpoints/src/main/scala/BreakpointTest.scala
- sbt-dap-plugin/src/sbt-test/attach/breakpoints/test
- sbt-dap-plugin/src/sbt-test/main/breakpoints/build.sbt
- sbt-dap-plugin/src/sbt-test/main/breakpoints/project/plugins.sbt
- sbt-dap-plugin/src/sbt-test/main/breakpoints/src/main/scala/BreakpointTest.scala
- sbt-dap-plugin/src/sbt-test/main/breakpoints/test
- sbt-dap-plugin/src/sbt-test/test/breakpoints/build.sbt
- sbt-dap-plugin/src/sbt-test/test/breakpoints/project/plugins.sbt
- sbt-dap-plugin/src/sbt-test/test/breakpoints/src/main/scala/Hello.scala
- sbt-dap-plugin/src/sbt-test/test/breakpoints/src/test/scala/BreakpointSpec.scala
- sbt-dap-plugin/src/sbt-test/test/breakpoints/test
Not entirely sure the return value is correct, I got the tip on analysis from: https://twitter.com/eed3si9n/status/1353456684430225408
> sbt plugin WIP

- .github/workflows/ci.yml
- build.sbt
- sbt-dap-plugin/src/main/scala/dap/DebugAdapterPlugin.scala
- sbt-dap-plugin/src/main/scala/dap/SbtDebuggeeRunner.scala
- sbt-dap-plugin/src/sbt-test/attach/breakpoints/pending
- sbt-dap-plugin/src/sbt-test/attach/breakpoints/project/plugins.sbt
- sbt-dap-plugin/src/sbt-test/attach/breakpoints/test
- sbt-dap-plugin/src/sbt-test/main/breakpoints/project/plugins.sbt
- sbt-dap-plugin/src/sbt-test/main/breakpoints/test
- sbt-dap-plugin/src/sbt-test/test/breakpoints/pending
- sbt-dap-plugin/src/sbt-test/test/breakpoints/project/plugins.sbt
- sbt-dap-plugin/src/sbt-test/test/breakpoints/test
Run scripted tests in CI
Also I have abandoned the idea of using the sbt `State` to store the debug servers. I now think it is unnecessary complexity.
> Add classpath and debug option

- core/src/main/scala/ch/epfl/scala/debug/internal/DebugSession.scala
- core/src/main/scala/ch/epfl/scala/debug/internal/Synchronized.scala
Fix https://github.com/scalacenter/bloop/pull/1444
> Fix Bloop DebugProtocolSpec

- sbt/plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/DebugAdapterPlugin.scala
- sbt/plugin/src/sbt-test/debug-session/aggregate/build.sbt
- sbt/plugin/src/sbt-test/debug-session/aggregate/project/plugins.sbt
- sbt/plugin/src/sbt-test/debug-session/aggregate/project/project/plugins.sbt
- sbt/plugin/src/sbt-test/debug-session/aggregate/src/main/scala/example/Hello.scala
- sbt/plugin/src/sbt-test/debug-session/aggregate/src/test/scala/example/HelloSpec.scala
- sbt/plugin/src/sbt-test/debug-session/aggregate/test
> Disable aggregation on debug session

- build.sbt
- core/src/test/scala/ch/epfl/scala/debugadapter/DebugServerSpec.scala
- core/src/test/scala/ch/epfl/scala/debugadapter/MainDebuggeeRunner.scala
- core/src/test/scala/ch/epfl/scala/debugadapter/ScalaDebugTestSuite.scala
- core/src/test/scala/ch/epfl/scala/debugadapter/ScalaVersions.scala
- project/Dependencies.scala
- project/plugins.sbt
Test breakpoints in Scala 2.12, Scala 2.13 and Scala 3
Fixes #31
Fixes #33
> Test debug Scala 2.12, 2.13 and 3

- .github/workflows/ci.yml
- build.sbt
- core/src/main/scala/ch/epfl/scala/debugadapter/internal/DebugAdapter.scala
- core/src/main/scala/ch/epfl/scala/debugadapter/internal/SourceLookupProvider.scala
> Use sbt client in CI

- core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/EvaluationProvider.scala
- core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Evaluator.scala
- core/src/test/scala/ch/epfl/scala/debugadapter/ScalaDebugTestSuite.scala
Fixes error: `Failed to get variables. Reason: com.sun.jdi.InvalidStackFrameException` which occurs after any expression evaluation.
> Fix JDI method invocation in expression evaluator

- core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Evaluator.scala
Every time I thought that I understand how the expression evaluator works it always turned out that I don't 😃 
So I decided to go through code and refactor parts which were hard to understand for me. I hope that now is easier to understand or at least not harder :D
> Refactor Evaluator.scala

- core/src/test/scala/ch/epfl/scala/debugadapter/ExpressionEvaluatorSuite.scala
Closes https://github.com/scalacenter/scala-debug-adapter/issues/116
Seems this was already fixed in a previously merged PR
> Add test for nested method evaluation

- core/src/main/scala/ch/epfl/scala/debugadapter/ClassPathEntry.scala
- core/src/test/scala/ch/epfl/scala/debugadapter/ExpressionEvaluatorSuite.scala
- core/src/test/scala/ch/epfl/scala/debugadapter/MainDebuggeeRunner.scala
- core/src/test/scala/ch/epfl/scala/debugadapter/ScalaDebugTestSuite.scala
- core/src/test/scala/ch/epfl/scala/debugadapter/ScalaInstanceCache.scala
About three times faster for `core / test`
> Speed up tests by class-loading and caching the compilers

- project/Developers.scala
> Add tdudzik and tgodzik as developers

- sbt/plugin/src/main/contraband/dap.contra
- sbt/plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/DebugAdapterPlugin.scala
- sbt/plugin/src/sbt-test/debug-session/test-selection-suite/build.sbt
- sbt/plugin/src/sbt-test/debug-session/test-selection-suite/project/plugins.sbt
- sbt/plugin/src/sbt-test/debug-session/test-selection-suite/project/project/plugins.sbt
- sbt/plugin/src/sbt-test/debug-session/test-selection-suite/src/test/scala/TestSuite.scala
- sbt/plugin/src/sbt-test/debug-session/test-selection-suite/test
PR in bsp repository: build-server-protocol/build-server-protocol/pull/304
> feat: scala test selection request

- sbt/plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/DebugAdapterPlugin.scala
- sbt/plugin/src/sbt-test/debug-session/attach/build.sbt
- sbt/plugin/src/sbt-test/debug-session/attach/test
> Fix attach remote

- core/src/test/scala/ch/epfl/scala/debugadapter/ScalaEvaluationTests.scala
- expression-compiler/src/main/scala-3/dotty/tools/dotc/evaluation/JavaEncoding.scala
- expression-compiler/src/main/scala-3/dotty/tools/dotc/evaluation/ResolveReflectEval.scala
Fix #246 
Also fix encoding of operator symbols in names.
> [Scala 3] Fix evaluation of private field in trait

- core/src/test/scala/ch/epfl/scala/debugadapter/ScalaEvaluationTests.scala
- expression-compiler/src/main/scala-3/dotty/tools/dotc/evaluation/InsertExpression.scala
> [Scala 3] evaluate expression on match or case def

- core/src/test/scala/ch/epfl/scala/debugadapter/ScalaEvaluationTests.scala
- expression-compiler/src/main/scala-3/dotty/tools/dotc/EvaluationContext.scala
- expression-compiler/src/main/scala-3/dotty/tools/dotc/evaluation/ExtractExpression.scala
- expression-compiler/src/main/scala-3/dotty/tools/dotc/evaluation/InsertExpression.scala
- expression-compiler/src/main/scala-3/dotty/tools/dotc/evaluation/ResolveReflectEval.scala
> Scala 3 evaluation of class def

- core/src/test/scala/ch/epfl/scala/debugadapter/ScalaEvaluationTests.scala
- expression-compiler/src/main/scala-3/dotty/tools/dotc/evaluation/InsertExpression.scala
> [Scala 3] Fix evaluation on assignment

- core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/ExpressionEvaluator.scala
> Evaluator uses classLoader of current this

- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/DebugSession.scala
- modules/sbt-plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/DebugAdapterPlugin.scala
- modules/sbt-plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/internal/DebuggeeProcess.scala
- modules/sbt-plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/internal/SbtDebuggee.scala
> Fix #409: Run setup during the task execution

- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/EvaluateNameUtilsProvider.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/ScalaProviderContext.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/JdiArray.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeDefaultEvaluator.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeDefaultValidator.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluation.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluationHelpers.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluatorExtractors.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeTree.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Validation.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/package.scala
- modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/DebugStepAssert.scala
- modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/DebugTestSuite.scala
- modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/RuntimeEvaluatorTests.scala
- modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/VariableEvaluationTests.scala
Fixes #453 & **Uses an updated version of java-debug**
At the same time I added some functionalities to test a local variable's value
> Array add to watch expression

- .github/workflows/ci.yml
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeDefaultValidator.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluationHelpers.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeTree.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Validation.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/package.scala
- modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/RuntimeEvaluatorTests.scala
- Updated Java versions on CI
- Added Java 20 in CI
- Check cross-compilation of `Test` in CI
- Fix runtime instanciation of inner class in Java 20
> Update Java versions on CI

- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeDefaultEvaluator.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeDefaultValidator.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluation.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluationHelpers.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluatorExtractors.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimePreEvaluationValidator.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimePrimitiveOp.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeTree.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Validation.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/package.scala
Fixes #480 
For now it simply print in the tests when an exceptions is thrown. Ideally it should be printed by a Logger, but I need to find a way to do so without having to pass it each time a `Validation` is instantiated
> Log exceptions

- .github/workflows/ci.yml
> Stop running scripted tests on Windows with Java 17

- modules/expression-compiler/src/main/scala-3/dotty/tools/dotc/evaluation/InsertExpression.scala
- modules/tests/src/test/scala/ch/epfl/scala/debugadapter/ScalaEvaluationTests.scala
> Add support for `-language:strictEquality`

- modules/sbt-plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/DebugAdapterPlugin.scala
- modules/sbt-plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/internal/SbtDebugToolsResolver.scala
- modules/sbt-plugin/src/sbt-test/debug-session/scala-collection-compat/build.sbt
- modules/sbt-plugin/src/sbt-test/debug-session/scala-collection-compat/project/build.properties
- modules/sbt-plugin/src/sbt-test/debug-session/scala-collection-compat/project/plugins.sbt
- modules/sbt-plugin/src/sbt-test/debug-session/scala-collection-compat/project/project/plugins.sbt
- modules/sbt-plugin/src/sbt-test/debug-session/scala-collection-compat/src/main/scala/example/Main.scala
- modules/sbt-plugin/src/sbt-test/debug-session/scala-collection-compat/test
> Scala212 sbt190

- modules/expression-compiler/src/main/scala-3/dotty/tools/dotc/evaluation/ExtractExpression.scala
- modules/tests/src/test/scala/ch/epfl/scala/debugadapter/ScalaEvaluationTests.scala
> no transform when inline

- modules/core/src/main/scala/ch/epfl/scala/debugadapter/JavaRuntime.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/stacktrace/RuntimeStepFilter.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/stacktrace/ScalaUnpickler.scala
- modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/TestingDebuggee.scala
- modules/tests/src/test/scala/ch/epfl/scala/debugadapter/StepFilterTests.scala
- modules/unpickler/src/main/scala/ch/epfl/scala/debugadapter/internal/stacktrace/Extractors.scala
- modules/unpickler/src/main/scala/ch/epfl/scala/debugadapter/internal/stacktrace/Scala3Unpickler.scala
- modules/unpickler/src/test/scala/ch/epfl/scala/debugadapter/internal/stacktrace/Scala3UnpicklerTests.scala
> Skip given lazy val getter

- build.sbt
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/Debuggee.scala
- modules/expression-compiler/src/main/scala-3/dotty/tools/dotc/evaluation/ExtractExpression.scala
- modules/expression-compiler/src/main/scala-3/dotty/tools/dotc/evaluation/ResolveReflectEval.scala
- modules/expression-compiler/src/test/scala-3.latest/ch/epfl/scala/debugadapter/ExpressionCompilerDebug.scala
- modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/TestingDebuggee.scala
- modules/tests/src/test/scala/ch/epfl/scala/debugadapter/ScalaEvaluationTests.scala
> Evaluation of static members

- modules/expression-compiler/src/main/scala-3/dotty/tools/dotc/evaluation/InsertExpression.scala
- modules/expression-compiler/src/test/scala-3.latest/ch/epfl/scala/debugadapter/ExpressionCompilerDebug.scala
- modules/tests/src/test/scala/ch/epfl/scala/debugadapter/ScalaEvaluationTests.scala
> Fix evaluation on extractor

- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/ClassEntryLookUp.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/IO.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/SourceEntryLookUp.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/SourceLookUpProvider.scala
- modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/TestingResolver.scala
- modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/ClassEntryLookUpStats.scala
Fix #541 
On my laptop it speeds up the loading of [gradle-api](https://repo1.maven.org/maven2/dev/gradleplugins/gradle-api/5.0/) from 140s to 1.8s.
> Re-use hot filesystem to read sources

- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeDefaultEvaluator.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeDefaultValidator.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluation.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluatorExtractors.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimePreEvaluationValidator.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeTree.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Validation.scala
- modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/RuntimeEvaluatorTests.scala
> Runtime assign

- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeDefaultValidator.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluationHelpers.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluatorExtractors.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeTree.scala
- modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/JavaRuntimeEvaluatorTests.scala
> fix evaluation in static context

- modules/sbt-plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/internal/DebuggeeProcess.scala
Fixes https://github.com/scalameta/metals-feature-requests/issues/352 when sbt is the build server.
> Log debuggee command with info level

- build.sbt
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/HotCodeReplaceProvider.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/HotCodeReplacer.scala
- modules/sbt-plugin/src/sbt-test/debug-session/hot-code-reload/build.sbt
- modules/sbt-plugin/src/sbt-test/debug-session/hot-code-reload/project/DebugState.scala
- modules/sbt-plugin/src/sbt-test/debug-session/hot-code-reload/src/main/scala/example/A.scala.1
- modules/sbt-plugin/src/sbt-test/debug-session/hot-code-reload/src/main/scala/example/A.scala.2
- modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/DebugStepAssert.scala
- modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/DebugTestSuite.scala
- modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/TestingDebugClient.scala
- modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/TestingDebuggee.scala
- modules/tests/src/test/scala/ch/epfl/scala/debugadapter/HotCodeReplaceTests.scala
- refactor the `HotCodeReplaceProvider`
- add more tests
- fix the hot code replace implementation
> Fix Hot code replace

- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/EvaluationProvider.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluation.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeTree.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeValidation.scala
- modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Safe.scala
- modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/TestingDebugClient.scala
- modules/tests/src/test/scala/ch/epfl/scala/debugadapter/SourceBreakpointTests.scala
- modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/RuntimeEvaluatorTests.scala
> fix #672: avoid GC on conditional breakpoint values

- modules/sbt-plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/internal/InternalTasks.scala
> [sbt plugin] check if `debugAdatperClassUpdates` is defined

- .github/workflows/release-expression-compiler.yml
Related to https://github.com/scalacenter/scala-debug-adapter/pull/733#discussion_r1698401633
> Release expression-compiler even if tests fail
