scalacenter/scala-debug-adapter

bloop-dap/src/main/scala/bloop/bsp/dap/BloopDebuggeeRunner.scala, bloop-dap/src/main/scala/bloop/bsp/dap/DebugSessionLogger.scala, build.sbt, core/src/main/scala/dap/CancelableFuture.scala, core/src/main/scala/dap/DebugServer.scala, core/src/main/scala/dap/DebugSession.scala, core/src/main/scala/dap/DebugSessionCallbacks.scala, core/src/main/scala/dap/DebuggeeRunner.scala, core/src/test/scala/dap/DebugServerSpec.scala, core/src/test/scala/dap/MainDebuggeeRunner.scala, core/src/test/scala/dap/MockDebuggeeRunner.scala, project/Dependencies.scala
This PR makes the `scala-debug-adapater` ready for integration with Bloop.
I've created a corresponding PR in Bloop to run the tests: https://github.com/scalacenter/bloop/pull/1444. We should keep it open and run the tests regularly until the core library is ready to be releases.
=> Integration with Bloop

sbt/plugin/src/main/contraband/dap.contra, sbt/plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/DebugAdapterPlugin.scala
Related to changes in https://github.com/sbt/sbt/pull/6397 and described in https://github.com/sbt/sbt/issues/6396
Adds support for the new field in `ScalaMainClass`. Uses copy of contraband schema to not depend on newer version of sbt. Conflicting imports are shaded with one defined in this project.
=> Environment variables in debug session

core/src/main/scala/ch/epfl/scala/debugadapter/internal/DebugAdapter.scala
Set `showStaticFields` setting to true so that object fields are shown in Scala 2.13 and Scala 3.
=> Enable show static variables

build.sbt, project/plugins.sbt, sbt/plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/DebugAdapterPlugin.scala, sbt/plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/internal/InternalTasks.scala
- Rename expression-compiler into scala-expression-compiler
- Make `resolveEvaluationClassLoader` a private and anonymous task
- Use `BuildInfo` to resolve the expression-compiler
=> Rework resolution of the Scala expression compiler

core/src/test/scala/ch/epfl/scala/debugadapter/DebugServerSpec.scala, core/src/test/scala/ch/epfl/scala/debugadapter/ExpressionEvaluatorSpec.scala, core/src/test/scala/ch/epfl/scala/debugadapter/MoreScala3DebugTest.scala, core/src/test/scala/ch/epfl/scala/debugadapter/ScalaDebugTestSuite.scala, sbt/plugin/src/sbt-test/debug-session/attach/build.sbt, sbt/plugin/src/sbt-test/debug-session/integration-test-suite/build.sbt, sbt/plugin/src/sbt-test/debug-session/main-class-scala3/build.sbt, sbt/plugin/src/sbt-test/debug-session/main-class/build.sbt, sbt/plugin/src/sbt-test/debug-session/step-into-jdk/build.sbt, sbt/plugin/src/sbt-test/debug-session/test-suite/build.sbt, test-client/src/main/scala/ch/epfl/scala/debugadapter/testing/TestDebugClient.scala
- Handle `(connect failed)` message
- Add more fine-grained control on the timeouts
The value of the timeouts can be tweaked later on each request if needed (for example, `evaluate` takes more time than  `setBreakpoints`)
=> Reduce the flakiness of the tests

core/src/test/scala/ch/epfl/scala/debugadapter/ExpressionEvaluatorSpec.scala, sbt/plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/internal/InternalTasks.scala, sbt/plugin/src/sbt-test/debug-session/no-expression-compiler/build.sbt, sbt/plugin/src/sbt-test/debug-session/no-expression-compiler/project/plugins.sbt, sbt/plugin/src/sbt-test/debug-session/no-expression-compiler/project/project/plugins.sbt, sbt/plugin/src/sbt-test/debug-session/no-expression-compiler/src/main/scala/example/Hello.scala, sbt/plugin/src/sbt-test/debug-session/no-expression-compiler/test, test-client/src/main/scala/ch/epfl/scala/debugadapter/testing/TestDebugClient.scala
When the expression compiler cannot be resolved, we should still be able to start a debug session, as before.
=> Test when expression compiler cannot be resolved

core/src/main/scala/ch/epfl/scala/debugadapter/internal/EvaluationProvider.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/ExpressionCompilationFailed.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/ExpressionEvaluator.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/JdiArray.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/JdiClassLoader.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/JdiClassObject.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/JdiObject.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/JdiPrimitive.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Safe.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/package.scala, core/src/test/scala/ch/epfl/scala/debugadapter/ExpressionEvaluatorSpec.scala, sbt/plugin/src/sbt-test/debug-session/no-expression-compiler/build.sbt
Objects created on the remote JVM can be garbage-collected at any time.
So during expression evaluation, we need to protect those by calling `disableCollection`.
We also need to call `enableCollection` after the expression evaluation succeeded or failed.
For reference, see https://stackoverflow.com/questions/25793688/life-span-of-jdi-mirrors-of-objects-living-in-a-remote-jvm
To do so I introduce a `Safe[T]` class which encapsulates the result of a computation on remote objects.
All remote are protected until one calls `safe.getResult`, which enables the garbage collection once again.
=> Prevent object reference from being collected

core/src/test/scala/ch/epfl/scala/debugadapter/DebugServerSpec.scala, core/src/test/scala/ch/epfl/scala/debugadapter/ExpressionEvaluatorSpec.scala, core/src/test/scala/ch/epfl/scala/debugadapter/ExpressionEvaluatorSuite.scala, core/src/test/scala/ch/epfl/scala/debugadapter/MainDebuggeeRunner.scala, core/src/test/scala/ch/epfl/scala/debugadapter/ScalaVersions.scala, expression-compiler/src/main/scala-2/scala/tools/nsc/EvalGlobal.scala, expression-compiler/src/main/scala-2/scala/tools/nsc/ExpressionCompiler.scala, test-client/src/main/scala/ch/epfl/scala/debugadapter/testing/TestDebugClient.scala
- fix expression evaluation on breakpoint with a definition or an assignment,
- revert to the non-interactive compiler to avoid `macro has not been expanded` error.
=> Fix expression evaluation

core/src/test/scala/ch/epfl/scala/debugadapter/ExpressionEvaluatorSuite.scala, expression-compiler/src/main/scala-2/scala/tools/nsc/EvalGlobal.scala
Previously, expression evaluator would fail if expression was a definition. Now, it will be wrapped in a block.
=> Always wrap single definition in block

core/src/test/scala/ch/epfl/scala/debugadapter/ExpressionEvaluatorSuite.scala, expression-compiler/src/main/scala-2/scala/tools/nsc/EvalGlobal.scala
Previously, we would create a new block at the breakpoint line, which could break the evaluated code when definition was present. Now, we instead input the expression into block stats, which no longer modifes the existing values.
Fixes https://github.com/scalacenter/scala-debug-adapter/issues/103
=> Fix expression evaluation when at definition

core/src/main/scala/ch/epfl/scala/debugadapter/internal/EvaluationProvider.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/ExpressionEvaluator.scala
When the classpath is too big and exceeds the maximum size of a command line, Bloop creates a `/tmp/jvm-forker-manifest2949990240171503800.jar` file which contains the classpath in a manifest file. But the Scala compiler does not support this and fails with:  `object scala in compiler mirror not found.`.
To fix this we pass the full classpath explicitly to the expression evaluator.
Tested locally:
```scala
package example
object Main {
def main(args: Array[String]): Unit = {
println(s"Classpath -> ${System.getProperty("java.class.path")}")
=>  println("Hello, World")
}
}
```
Classpath is `/tmp/jvm-forker-manifest5241138918947448719.jar` and expression evaluation does work.
=> Fix #148: Pass classpath to ExpressionEvaluator

core/src/main/scala/ch/epfl/scala/debugadapter/internal/EvaluationProvider.scala
Related to https://github.com/scalameta/metals/issues/2011
I thought it might be possible to use Java expression evaluator, but turns out you need OSGI for it.
=> Don't allow expression evaluation in Java files

core/src/main/scala/ch/epfl/scala/debugadapter/ClassSystem.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/ClassEntryLookUp.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/IO.scala, core/src/test/scala/ch/epfl/scala/debugadapter/internal/ClassEntryLookUpSpec.scala
It seems if we are unable to read a source jar, not debug session will be started currently. This can happen if we get a broken source jar such as the one in https://github.com/scalameta/metals/issues/3584
Tested it manually and it seems to help.
=> Run even if some source jars are corrupted

sbt/plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/DebugAdapterPlugin.scala
Fixes #262 
Changed to `run / baseDirectory`, but this could be narrowed down even to `Compile / run / baseDirectory` if being the most strict.
The builds, where the most generic `baseDirectory` was changed should continue to work w/o breakage.
Can retarget this to `2.2.x` if this makes any sense.
=> Use run / baseDirectory for debugger

core/src/main/scala/ch/epfl/scala/debugadapter/internal/ClassEntryLookUp.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/SourceLookUpProvider.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/StepFilterProvider.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/scalasig/Decompiler.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/stepfilter/ClassLoadingFilter.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/stepfilter/RuntimeStepFilter.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/stepfilter/Scala2StepFilter.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/stepfilter/Scala3StepFilter.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/stepfilter/ScalaStepFilter.scala, core/src/main/scala/ch/epfl/scala/debugadapter/internal/stepfilter/StepFilter.scala, project/Dependencies.scala, tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/DebugTestSuite.scala, tests/src/test/scala/ch/epfl/scala/debugadapter/ScalaDebugTests.scala, tests/src/test/scala/ch/epfl/scala/debugadapter/ScalaEvaluationTests.scala
The java-debug 0.34.0+8 uses the `IStepFilterProvider` to know if a breakpoint should stop or not.
=> Use IStepFilterProvider to skip breakpoints

modules/core/src/main/scala/ch/epfl/scala/debugadapter/testing/TestSuiteEvent.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/testing/TestSuiteEventHandler.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/testing/TestSuiteSummary.scala
reported in https://github.com/scalameta/metals-vscode/issues/1296.
- change `testSuiteResult.duration` to `e.duration`
- extract `TestSuiteEventHandler` to separate file, I think it deserves that
- add some random thoughts scaladoc
=> fix: use event duration instead of whole suite result's duration when making a summary

build.sbt
@lefou Next version of the scala-debug-adapter will have Scala 2.13 support.
=> Register scala-debug-adapter_2.13 for publication

.github/workflows/ci.yml, .github/workflows/manual-release.yml, .github/workflows/release.yml, build.sbt
So this is in relation to https://github.com/scalacenter/scala-debug-adapter/issues/375. It looks like when we originally tried publishing this it failed due to flakiness on the Sonatype side. However, I tried again today and it also [failed](https://github.com/scalacenter/scala-debug-adapter/actions/runs/4016899774/jobs/6974689747#step:4:1274), but it seems valid:
```
2023-01-31 11:58:26.157Z error [SonatypeClient] [promote] Failed  - (SonatypeClient.scala:191)
2023-01-31 11:58:26.157Z error [SonatypeClient] Activity name:release, started:2023-01-31T11:58:12.127Z, stopped:2023-01-31T11:58:23.741Z  - (SonatypeClient.scala:467)
2023-01-31 11:58:26.159Z error [SonatypeClient]     Failed: RepositoryWritePolicy, failureMessage:Artifact updating: Repository ='releases:Releases' does not allow …
```
=> fix: prepare for 3.0.7 by bumping java-debug

.github/workflows/release-expression-compiler.yml, .github/workflows/release-full.yml, build.sbt, modules/core/src/main/scala/ch/epfl/scala/debugadapter/ScalaVersion.scala, modules/tests/src/test/scala/ch/epfl/scala/debugadapter/ScalaEvaluationTests.scala
\+ Make the java-debug version configurable using an env var.
=> Fix tests on releasing RC versions of the expresion-compiler

modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/JdiClass.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/JdiObject.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/ScalaEvaluator.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/package.scala
Since we received an ObjectCollectedException in this [CI run](https://github.com/scalacenter/scala-debug-adapter/actions/runs/4891776345/jobs/8732717063?pr=405), it is likely that I forgot to wrap some jdi `ObjectReference` into a `Safe`. Here I found and fix one case which is the exception in `InvocationException`.
=> Try fix ObjectCollectedException

modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/EvaluationProvider.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluator.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluatorExtractors.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeTree.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Validation.scala, modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/RuntimeEvaluatorTests.scala
There was a bug with my first implementation. Given the following code
```scala
case class Foo() {
case class FriendFoo() {
case class InnerFriendFoo() { val str = "inner friend foo"}
object InnerFriendFoo { val str = "object inner friend foo"}
}
object FriendFoo
def friendFoo = FriendFoo
}
```
Calling `Foo().friendFoo.InnerFriendFoo.str` could pass the validation even if incorrect
The reason was a bad management of module & nested type name encoding. `Foo().friendFoo` is typed as `Foo$FriendFoo$` and `Foo$FriendFoo$InnerFriendFoo$` is the encoded name of `InnerFriendFoo`. So it passed validation
=> Module lookup fix

modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/EvaluationProvider.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluationHelpers.scala, modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/RuntimeEvaluatorTests.scala
Fixes #445 
I also removed the filter on private methods, we might want to be able to call them. Extra caution is required when these methods have side effects though
=> Method boxing overloads + added private methods

build.sbt, modules/scala-3-step-filter/src/main/scala/ch/epfl/scala/debugadapter/internal/stepfilter/ScalaStepFilterBridge.scala, modules/scala-3-step-filter/src/test/scala/ch/epfl/scala/debugadapter/internal/stepfilter/ScalaStepFilterBridgeTests.scala, modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/DebugStepAssert.scala, modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/FakeJdiLocalVariable.scala, modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/FakeJdiMethod.scala
- Fix formatting of `TermRef` from `x` to `x.type`
- Refactor formatting in `ScalaStepFilterBridge` and `ScalaStepFilterBridgeTests`
- Add formatting of package objects and top level definitions
@aymanelamyaghri FYI I implemented the formatting of package object and top level definitions.
=> Refactor ScalaStepFilterBridge and its tests

modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/JdiArray.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeDefaultEvaluator.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeDefaultValidator.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluation.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluationHelpers.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluatorExtractors.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeTree.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Validation.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/package.scala, modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/RuntimeEvaluatorTests.scala
=> Apply method and arrays

modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeDefaultEvaluator.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeDefaultValidator.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluation.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluationHelpers.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluatorExtractors.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimePreEvaluationValidator.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeTree.scala, modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/JavaRuntimeEvaluatorTests.scala, modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/RuntimeEvaluatorTests.scala
Allows to evaluate (and eventually pre-evaluate) flow control at runtime. For instance
```scala
case class Test(i: Int)
def test(t: Test) = s"test ${t.i}"
if (true) 1 else 2                    // res0: Int = 1
(if (true) Test(1) else Test(2)).i    // res1: Int = 1
(if (true) Test(1) else 2).i          // res2: Int = 1 thanks to pre-evaluation
test(if(true) Test(1) else 1)         // res3: String = "test 1"
(if (m()) Test(1) else 2).i          // fails because the `if` cannot be pre-evaluated
```
=> Evaluate flow control

modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/stacktrace/Scala2Unpickler.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/stacktrace/Scala3Unpickler.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/stacktrace/ScalaUnpickler.scala, modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/FakeJdiMethod.scala, modules/unpickler/src/main/scala/ch/epfl/scala/debugadapter/internal/jdi/Method.scala, modules/unpickler/src/main/scala/ch/epfl/scala/debugadapter/internal/stacktrace/Scala3Unpickler.scala, modules/unpickler/src/test/scala/ch/epfl/scala/debugadapter/internal/stacktrace/Scala3UnpicklerTests.scala
- Differentiate getter and method with same name
- Catch all exceptions in `ScalaUnpickler`
=> Fix #491: Differentiate getter and method with same name

modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/EvaluationProvider.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/SourceEntrySearchTree.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/SourceLookUpProvider.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/JdiClassLoader.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/JdiObject.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeDefaultEvaluator.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeDefaultValidator.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluation.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluationHelpers.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeEvaluatorExtractors.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimePreEvaluationValidator.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/RuntimeTree.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/package.scala, modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/RuntimeEvaluatorTests.scala
=> Multiple outers

modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/stacktrace/ScalaUnpickler.scala, modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/TestingDebugClient.scala, modules/tests/src/test/scala/ch/epfl/scala/debugadapter/StepFilterTests.scala, modules/unpickler/src/main/scala/ch/epfl/scala/debugadapter/internal/stacktrace/Scala3Unpickler.scala
Fixes #332 
Only works for Scala 2 as there are no methods named `xxx$access$\d+` in Scala 3
Also remvoved `final` attribute from `FakeJdiMethod` and `FakeJdiType` to be able to create anon classes to solve `NotImplementedError` at call site
=> Skip private accessors

modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/stacktrace/RuntimeStepFilter.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/stacktrace/ScalaUnpickler.scala, modules/tests/src/test/scala/ch/epfl/scala/debugadapter/StepFilterTests.scala, modules/unpickler/src/main/scala/ch/epfl/scala/debugadapter/internal/stacktrace/Scala3Unpickler.scala
=> Skip exported methods and BoxeRuntimes

.github/workflows/ci.yml
I thought it might be useful to be able to skip the tests (when only doc is changed or when we're on a "WIP WIP branch"), to avoid running them unnecessarily
=> added a skip-ci

modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/ClassEntryLookUp.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/SourceEntryLookUp.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/SourceLookUpProvider.scala, modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/ClassEntryLookUpSpec.scala, modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/MetalsClassBreakpointSuite.scala
This PR changes ClassEntryLookup so that it can lookup sourceFile URIs in a case-insensitive on case-insensitive file-systems.
For instance, on Windows, "file:///C/MyProject/A.scala" should map to the same objects as "file:///C:/myProject/A.scala". 
This PR should fix:
* This should fix scalameta/Metals issue [#3747](https://github.com/scalameta/metals/issues/3747)
* #614 
Solution Notes: 
- The maps in ClassEntryLookup now are keyed with a new SourceFileKey class that abstracts the URI and how it is represented.
- For Windows/Mac: 
- For “file” scheme URIs, the comparison of the file part of the URI is compared in a case-insensitive way.
- For “jar” scheme URIs, the comparison of the file part of the URI is compared in a case-insensitive way, but the jar-contents part is compared in …
=> Make ClassEntryLookup accommodate case-insensitive lookups where appropriate

modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/IO.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/SourceEntryLookUp.scala
connected to: https://github.com/scalameta/metals/issues/5928
We want to start scala debug adapter from Metals for build servers that don't support it. In Metals FileSystems for jars are created and kept open to be reused.
=> improvement: Use existing file system when available and don't close it

modules/core/src/main/scala/ch/epfl/scala/debugadapter/DebugConfig.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/DebugServer.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/DebugSession.scala, modules/sbt-plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/DebugAdapterPlugin.scala, modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/DebugTestSuite.scala, modules/tests/src/test/scala/ch/epfl/scala/debugadapter/DebugServerTests.scala
This should solve a memory leak in the debugger.
=> Automatically close debug server after terminated event

modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/SourceLookUpProvider.scala
Refactored SourceLookUpProvider.loadClassesByScalaName() to be more efficient. 
The issue presented itself in 4.0.0 (related to the HotCodeReplace feature). The debug loading times became really slow.
On my large project, the loading went from 75s back to a normal 12s. (12s is about what I saw in v3.1.6).  
This should resolve https://github.com/scalameta/metals/issues/6544
=> Improved Performance of loadClassesByScalaName

modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/SourceLookUpProvider.scala
If 2 entries contain the same class name, the first class should shadow the second class, because that the one loaded by the JDK `ClassLoader`.
Conicidentally that should fix https://github.com/scalameta/metals/issues/5807.
=> Reverse entries in `SourceLookUpProvider`

modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/ClassEntryLookUp.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/SourceLookUpProvider.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/JdiClassLoader.scala, modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/stacktrace/JdiExtensions.scala, modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/ClassEntryLookUpSpec.scala, modules/tests/src/test/scala/ch/epfl/scala/debugadapter/internal/MetalsClassBreakpointSuite.scala
Try fix #780 
- Replace `argumentTypes` by `argumentTypeNames`
- Fix `isAnonFunction` matcher on Scala 2
- Cache scala sigs in `ClassEntryLookUp`
=> Improve perf of Scala2Decoder

modules/sbt-plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/DebugAdapterPlugin.scala
Currently we're observing an envvar parse bug in metals + sbt bsp mode:
- an envvar whose value includes `=` is stripped of them
- e.g., "ENV=ZGlkIHlvdSB0cnkgZGVjb2RpbmcgdGhpcz8=" loses `=` at the end
- an envvar whose value is empty is omitted.
- e.g., "ENV=" are not injected into the debuggee.
This PR tries to fix these issue.
Example:
=> fix(DebugAdaptorPlugin): parsing envVars with edge cases
